### PR TITLE
Add migrator for `build.tools`

### PR DESCRIPTION
**Pull request by astrojuanlu**
Example output:

```
$ python -m readthedocs_assistant.cli
INFO:__main__:readthedocs-assistant/jupyterlite created
INFO:__main__:Current config: {'version': 2, 'conda': {'environment': 'docs/environment.yml'}, 'sphinx': {'builder': 'html', 'configuration': 'docs/conf.py', 'fail_on_warning': True}}
INFO:__main__:New config: {'version': 2, 'conda': {'environment': 'docs/environment.yml'}, 'sphinx': {'builder': 'html', 'configuration': 'docs/conf.py', 'fail_on_warning': True}, 'build': {'os': 'ubuntu-20.04', 'tools': {'python': '3.7'}}}
```

### CODE REVIEW

**Comment by astrojuanlu** [comment]
Reviewed this with @humitos 🙌🏽 noted some of his comments and ideas as `# TODO`s in the PR.

**Comment by astrojuanlu** [comment]
Will address the `#FIXME` comments in this PR, the `#TODO` ones in subsequent PRs.

**Comment by astrojuanlu** [comment]
@humitos made another good point avoid preserving the style of the YAML file, in particular the indentation. A quick search tells us that this is a difficult problem: https://stackoverflow.com/a/60891175/554319

> If you are using Python, using [ruamel](https://yaml.readthedocs.io/en/latest/example.html) will help you preserve quite some formatting since it implements round-tripping up to native structures. However, it isn't perfect and cannot preserve all formatting.
> ...
> YAML has not been designed for this task. In fact, it has been defined as a serialization language, assuming that your data is authored as native data structures in some programming language and from there dumped to YAML. However, in reality, YAML is used a lot for configuration, meaning that you typically write YAML by hand and then load it into native data structures.
> ...
> This contrast is the reason why it is so difficult to modify YAML files while preserving formatting: The YAML format has been designed as transient data format, to be written by one application, and then to be loaded by another (or the same) application. In that process, preserving formatting does not matter. It does, however, for data that is checked-in to version control (you want your diff to only contain the line(s) with data you actually changed), and other situations where you write your YAML by hand, because you want to keep style consistent.
> There is no perfect solution for changing exactly one data item in a given YAML file and leaving everything else intact. Loading a YAML file does not give you a view of the YAML file, it gives you the content it describes. Therefore, everything that is not part of the described content – most importantly, comments and whitespace – is extremely hard to preserve.

**Comment by astrojuanlu** [comment]
Welp, this took a while. https://github.com/python/mypy/issues/11988

**Comment by astrojuanlu** [comment]
Current status:

```
$ python -m readthedocs_assistant.cli
INFO:__main__:Current config: {'version': 2, 'conda': {'environment': 'docs/environment.yml'}, 'sphinx': {'builder': 'html', 'configuration': 'docs/conf.py', 'fail_on_warning': True}}
INFO:__main__:New config: {'version': 2, 'conda': {'environment': 'docs/environment.yml'}, 'sphinx': {'builder': 'html', 'configuration': 'docs/conf.py', 'fail_on_warning': True}, 'build': {'os': 'ubuntu-20.04', 'tools': {'python': '3.7'}}}
INFO:__main__:Migration was applied and configuration was changed, pull request is required
INFO:__main__:readthedocs-assistant/jupyterlite created
```

**Comment by astrojuanlu** [comment]
Good enough for now. Merging!

**Review by humitos — APPROVED** [review]
🧉

**Pull request merged**
