### PR TITLE
Propose changes

### PR DESCRIPTION
**Pull request by astrojuanlu**
Current status:

```
$ python -m readthedocs_assistant.cli
INFO:__main__:Current config: {'version': 2, 'conda': {'environment': 'docs/environment.yml'}, 'sphinx': {'builder': 'html', 'configuration': 'docs/conf.py', 'fail_on_warning': True}}
INFO:__main__:New config: {'version': 2, 'conda': {'environment': 'docs/environment.yml'}, 'sphinx': {'builder': 'html', 'configuration': 'docs/conf.py', 'fail_on_warning': True}, 'build': {'os': 'ubuntu-20.04', 'tools': {'python': '3.7'}}}
INFO:__main__:Migration was applied and configuration was changed, pull request is required
INFO:__main__:readthedocs-assistant/jupyterlite created
INFO:__main__:New branch created successfully
INFO:__main__:Contents updated successfully
INFO:__main__:Browse https://github.com/readthedocs-assistant/jupyterlite/compare/main...assistant-update-config to see the changes
```

Screenshot 2022-01-13 at 22-44-42 Comparing main assistant-update-config · readthedocs-assistant jupyterlite

This is the produced diff:

```diff
  version: 2
- 
+ build:
+   os: ubuntu-20.04
+   tools:
+     python: '3.7'
  conda:
    environment: docs/environment.yml
- 
  sphinx:
    builder: html
    configuration: docs/conf.py
    fail_on_warning: true
```

Found how to control the order of the keys (good!) but didn't investigate yet how to add some whitespace.

### CODE REVIEW

**Comment by astrojuanlu** [comment]
Remaining tasks:

- [x] Replace hardcoded parameters by proper CLI interface (typer? click? plain argparse?)
- [x] Write actual mamba migration and enable migrator choice from CLI
- [ ] ~Write code to make actual pull request, including a message template~ (see below)

**Comment by astrojuanlu** [comment]
Okay, Houston, we've had a problem [here](https://docs.github.com/en/rest/reference/pulls#create-a-pull-request).

> To open or update a pull request in a public repository, you must have write access to the head or the source branch.

So, to my understanding, we'd have to create an app that the user would authorize to make changes to their repo, similarly to what pyup does (which actually creates a new branch _in the repo it's updating_, see for instance https://github.com/readthedocs/readthedocs.org/pull/8817.

Until we figure that out, this will be a helper, but won't be able to automate anything.

I'm merging the pull request so we can continue the discussion from there.

**Comment by humitos** [comment]
> To open or update a pull request in a public repository, you must have write access to the head or the source branch.

I didn't know about this. I suppose it makes sense to avoid spam creating PR programmatically. I understand that we cannot create the PR with the script (and without being a GH app) but we can open that link and create the PR manually with the `readthedocs-assistant` user account, right? If that's the case, it's not perfect, but we will still have 90% of the work done automatically at least.

**Comment by astrojuanlu** [comment]
Yep, that's right! It can be a helper for us at least.

**Pull request merged**
